# Generated by Django 5.0.6 on 2024-06-06 05:28

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_first_name', models.CharField(max_length=100)),
                ('driver_middle_name', models.CharField(max_length=100)),
                ('driver_last_name', models.CharField(max_length=100)),
                ('driver_type', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_parking.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experation_date', models.DateField(max_length=100)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_parking.vehicle')),
            ],
        ),
    ]