# Generated by Django 5.0.6 on 2024-06-13 03:18

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('u_parking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permit',
            old_name='vehicle_id',
            new_name='vehicle',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='driver_id',
            new_name='driver',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='experation_date',
        ),
        migrations.AddField(
            model_name='permit',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='permit',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='permit',
            name='permit_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='permit',
            name='purchase_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='license_plate_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]